### PR TITLE
Add Rules

### LINKED ISSUE #18: Draft rules for tweet contents
Let's use this thread to propose ideas for rules that will be collated later into a checklist that moderators can use to approve or reject tweet proposals.

Once we have a strict canonical set, which will be used for `eth_classic`, we can then create another set of modifications for `ETC_Network`, which can be looser.

---

I'll start 

There should be limits on what kind of tweets are published

- No spam
- No scams
- No drama
- Stay classy

Anything else?

### PR DESCRIPTION
**Pull request by IstoraMandiri**
Fixes #18 , please review and make suggestions.

### CODE REVIEW

**Review by w1g0 — CHANGES_REQUESTED** [review]
Removal of line 53 -> 58

This is content for @ETC_Network imho

**Comment by IstoraMandiri** [comment]
Looks like @bobsummerwill agrees with you @w1g0 

https://twitter.com/BobSummerwill/status/1581633468441976836

> Very unlikely. The account is NOT for promotion of specific projects. The website is there as a directory for people to find things.

I wonder if there are limits to this though - what about the examples given in the comments above?

**Comment by w1g0** [comment]
Didn't check the tweets, and examples are "coming soon", so which ones are you referring to?

**Comment by IstoraMandiri** [comment]
Perhaps you missed it because I created it as part of a review. I'll stick to regular comments from now.

> I figured this one would be controversial, but the reasoning I have it like this is that I think that it becomes difficult to draw a line. Should this account really never tweet out third party projects?
> 
> If Mantis or Besu had a release or security problem, should ignore that?
> 
> If MetaMask decided to support ETC by default,, we should not tweet this?
> 
> What if an ETC ETF was launched by Greyscale?
> 
> Perhaps a compromise would be that this account is not used for small projects, but only big projects such as the examples given?

**Comment by w1g0** [comment]
> Projects from **small lesser known** project must be linked to via the website, which includes a disclaimer, must include a disclaimer within the tweet.

None of these are small projects. Exceptions to **larger known** projects seems reasonable to retweet with text.

**Comment by IstoraMandiri** [comment]
@w1g0 cool, let's update that then.

"Large" should would be those projects that have been around for at least 2 years and likely to be known about by most people following ETC.

**Comment by w1g0** [comment]
Line 57 "Tether-ETC" maybe better to put "ETC/Tether"
it's very unlikely that Binance will use ETC as denominator ^^

**Comment by IstoraMandiri** [comment]
By Tether-ETC I meant a version of Tether deployed to ETC.

**Comment by w1g0** [comment]
> (e.g. Binance listing TetherETC/ETC pair, ...

(e.g. Binance listing USDT Tether tokens on the ETC blockchain, ...

**Review by w1g0 — COMMENTED** [review]
Still not in favor of the crediting system mentioned in line 70

**Review by TheCrowbill — COMMENTED** [review]
There are several minor usage and syntax errors throughout the new text.

Instead of listing them all here individually, may I edit the file directly?

**Comment by IstoraMandiri** [comment]
> There are several minor usage and syntax errors throughout the new text.
> 
> Instead of listing them all here individually, may I edit the file directly?

Yes, please do!

**Comment by TheCrowbill** [comment]
> > There are several minor usage and syntax errors throughout the new text.
> > Instead of listing them all here individually, may I edit the file directly?
> 
> Yes, please do!

Done.

**Comment by IstoraMandiri** [comment]
Awesome, thank you @TheCrowbill !

**Review by justjinn — COMMENTED** [review]
- Very well written.

- Under new project announcements, may want to add a line or something to minimize scam potential (how will the scam-o-meter be gauged).

- Also may want to add something about new nft project announcements (remembering the time when ETC NFTs started to populate and eth_classic was getting heat for not promoting all NFTs).


Thinking out loud. 
💚

**Review by TheCrowbill — APPROVED** [review]
IMO, this is ready to merge and any changes needed going forward can be done from there.

**Comment by IstoraMandiri** [comment]
> IMO, this is ready to merge and any changes needed going forward can be done from there.

Agree, please help merge this @ethereumclassic/tweeters .

**Review by justjinn — APPROVED** [review]

**Comment by IstoraMandiri** [comment]
@TheCrowbill please could you undo the removal third parties? 

@w1g0 mentioned above that it's reasonable for large projects such as those in the examples.

At least, please discuss before updating this PR.

**Comment by TheCrowbill** [comment]
> 

Yes.

If resolved, why are the requested changes still blocking merge?

**Comment by TheCrowbill** [comment]
Third Party Projects section has been replaced without alteration.

**Review by TheCrowbill — APPROVED** [review]
AFAIK, this is ready for merge.

**Comment by IstoraMandiri** [comment]
@TheCrowbill yep, just need one more approval.

**Review by brolal — APPROVED** [review]

**Pull request merged**
