### PR TITLE
Create 20221011-Sound-Money.tweet

### PR DESCRIPTION
**Pull request by Jamyye**
Getting that tweeter going with some website content.

### CODE REVIEW

**Comment by IstoraMandiri** [comment]
LGTM

https://github.com/ethereumclassic/tweets-eth_classic/actions/runs/3228739217/jobs/5285262531#step:3:8

**Review by w1g0 — CHANGES_REQUESTED** [review]
Sound money can't have any superlative. It's either sound money or not, so the most sound money doesn't exist. Great tweet initiative, let's change by removing "the most" and push this 👍

**Comment by w1g0** [comment]
> Formatting LGTM
> 
> https://github.com/ethereumclassic/tweets-eth_classic/actions/runs/3228739217/jobs/5285262531#step:3:8
> 
> Not sure about the wording though - "the most sound money", perhaps just "Why ETC is Sound Money" ?

Lol, you beat me to it 😂

**Review by IstoraMandiri — APPROVED** [review]

**Comment by Jamyye** [comment]
Thank you all :) I agree

**Pull request merged**
