### PR TITLE
First attempt at a thread of tweets.

### PR DESCRIPTION
**Pull request by bobsummerwill**
In this case replacing tweets 2,3,4 of this announcement of this twitter-together support because the link to the repo for the tweets was pointing to etc_network not eth_classic.

### CODE REVIEW

**Review by w1g0 — CHANGES_REQUESTED** [review]
In third tweet I would be more explicit about "this account" and make it "@eth_classic which will be the main account" maybe even mentioning that we are taking steps to get it verified.

With the fourth tweet, I think maybe to open a new issue in the respective repo with a reference to the mentioned issue #15

ps: why is the preview only approving 1 out of 4 tweets?

**Review by w1g0 — APPROVED** [review]

**Review by gitr0n1n — APPROVED** [review]

**Comment by w1g0** [comment]
Fire away @bobsummerwill!

**Review by gitr0n1n — APPROVED** [review]

**Review by brolal — APPROVED** [review]

**Comment by bobsummerwill** [comment]
Very annoyingly, the preview image here still shows some old/cached version with "NOT LIVE YET!" prominent. But that cannot be fixed.

https://twitter.com/eth_classic/status/1580266558840004608?s=46&t=nDsha08AohGW3IAG7uCWQQ

**Comment by IstoraMandiri** [comment]
Glad the thread worked, as expected, even without the preview.

The cached preview may sort itself out over time on Twitter's side.

**Pull request merged**
